### ISSUE TITLE
Standardizing workspace and boot libraries

### ISSUE THREAD

**Issue by jcstrang-edu** [briantdavis/eas_bbb_version1#13]
To be discussed at next meeting:

Dr. Davis and I have discussed standardizing the workspace/repository location so that the init script doesn't have to fish the beaglebone for the appropriate executeable.

Standardization will ensure that we either will or will not execute the correct files everytime the beaglebone is turned on.

Because the init script is a boot-loaded file, it inherently has lower-than-or-equal-to-root access. So, location is not an issue.

I currently have my master branch in the base ("/") directory, but it would not be unreasonable to have the branch in the "/root" directory (or any other).

Thoughts?

**Comment by jcstrang-edu** [comment]
As discussed in the meeting on feb 8th of 2016:

Redesign the repository to a standardized directory the root directory.

This may likely be : "/EAS"

Under this, there will be relevant folders such as "./boot/" for initialization scripts "./source" for compileable code, "./DAQ" for executable data acquisition, and others as necessary.

This makes it easier to clone the repository directly into the team directory.

"./logs" directory may need to be made; this directory might need to be added to the ".gitignore" to avoid including it in the repository.

**Comment by briantdavis** [comment]
Repo re-organized as consistent with the discussion.  If this satisfies the issue, I will close #13, if not, let me know how, or commit changes yourself which modify structure.

**Comment by briantdavis** [comment]
Closed Live @ meeting 10-Feb, directory structure acceptable to team. /docs /decoder to be added.
